# Site settings
title: Ren Gibbons
subtitle:
email: gibbons.ren (at) gmail (dot) com
description: MY PERSONAL WEBPAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Ren Gibbons
street_address:
city: Oakland
state: CA
zip_code: 94618
country: United States of America
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/rengibbons
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/rengibbons
linkedin_url: http://www.linkedin.com/in/ren-gibbons-489890142
pinterest_url:
slack_url:
twitter_url:

# Google Analytics
google_analytics:

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag
