# Site settings
title: Ren Gibbons
subtitle:
email: gibbons.ren (at) gmail (dot) com
description: MY PERSONAL WEBPAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Ren Gibbons
street_address:
city: Oakland
state: CA
zip_code: 94618
country: United States of America
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/rengibbons
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/rengibbons
linkedin_url: http://www.linkedin.com/in/ren-gibbons-489890142
pinterest_url:
slack_url:
twitter_url:

# Google Analytics
google_analytics:

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag

# Keep as drafts: content is still in the repo but excluded from the built site
exclude:
 - cycling.md
 - hiking.md
 - running.md
 - woodworking.md
 - assets/images/pct
 - assets/images/rg_hike_1.JPG
 - assets/images/rg_hike_2.JPG
 - assets/images/rg_hike_3.jpg
 - assets/images/rg_run_boston_1.jpg
 - assets/images/rg_run_boston_2.jpg
 - assets/images/rg_run_diablo.JPG
 - assets/images/rg_run_nf.jpg
 - assets/images/rg_ww1.JPG
 - assets/images/rg_ww2.JPG
 - assets/images/rg_ww3.JPG
 - assets/images/rg_ww4.png
 - assets/images/rg_ww5.JPG
 - assets/images/rg_ww8.JPG
 - assets/images/rg_ww8.png
 - assets/images/rg_ww9.png
 - assets/images/rg_ww10.png
 - assets/images/rg_ww11.png
